<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.huongdanjava.systemdesign.sagapattern</groupId>
    <artifactId>saga-pattern-orchestrator-example</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>common</artifactId>

  <properties>
    <maven.compiler.source>26</maven.compiler.source>
    <maven.compiler.target>26</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
      <version>3.0.0</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.14.0</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <version>5.5.0</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>logging-interceptor</artifactId>
      <version>5.5.0</version>
      <scope>compile</scope>
    </dependency>

    <dependency>
      <groupId>io.gsonfire</groupId>
      <artifactId>gson-fire</artifactId>
      <version>1.9.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>

        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/api/common-api.yml</inputSpec>
              <generateApis>false</generateApis>
              <generateModels>true</generateModels>
              <!--              <generateSupportingFiles>false</generateSupportingFiles>-->
              <generateModelTests>false</generateModelTests>
              <!--              <artifactId>${project.name}</artifactId>-->
              <!--              <groupId>com.huongdanjava.systemdesign.sagapattern.${service.package}</groupId>-->
              <generatorName>java</generatorName>
              <modelPackage>com.huongdanjava.systemdesign.sagapattern.web.dto
              </modelPackage>
              <configOptions>
                <useJakartaEe>true</useJakartaEe>
                <!--                <delegatePattern>true</delegatePattern>-->
                <!--                <useSpringBoot4>true</useSpringBoot4>-->
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>