version: '3.9'

services:
  spring-boot-websocket_1:
    image: spring-boot-websocket
    container_name: spring-boot-websocket_1
    ports:
      - 8081:8080
    networks:
      - huongdanjava
      
  spring-boot-websocket_2:
    image: spring-boot-websocket
    container_name: spring-boot-websocket_2
    ports:
      - 8082:8080
    networks:
      - huongdanjava
     
  spring-boot-websocket_3:
    image: spring-boot-websocket
    container_name: spring-boot-websocket_3
    ports:
      - 8083:8080
    networks:
      - huongdanjava
      
  nginx:
    image: nginx:0.0.1
    container_name: nginx
    ports:
      - 80:80

networks:
  huongdanjava:
    driver: bridge