version: '3.9'

services:
  spring-boot-websocket_1:
    image: spring-boot-websocket
    container_name: spring-boot-websocket_1
    ports:
      - 8081:8080
    networks:
      - huongdanjava
      
  spring-boot-websocket_2:
    image: spring-boot-websocket
    container_name: spring-boot-websocket_2
    ports:
      - 8082:8080
    networks:
      - huongdanjava
     
  spring-boot-websocket_3:
    image: spring-boot-websocket
    container_name: spring-boot-websocket_3
    ports:
      - 8083:8080
    networks:
      - huongdanjava
      
  rabbitmq:
    image: rabbitmq:0.0.1
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - ~/Documents/data/rabbitmq/data/:/var/lib/rabbitmq
      - ~/Documents/data/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - huongdanjava
      
  nginx:
    image: nginx:0.0.1
    container_name: nginx
    ports:
      - 80:80

networks:
  huongdanjava:
    driver: bridge