version: '3.9'

services:
  spring-boot-websocket_1:
    image: spring-boot-websocket
    container_name: spring-boot-websocket_1
    environment:
      DATABASE_USERNAME: "khanh"
      DATABASE_PASSWORD: "123456"
      DATABASE_HOST: "postgresql"
      DATABASE_NAME: "test"
      DATABASE_PORT: 5432
    ports:
      - 8081:8080
    networks:
      - huongdanjava
      
  spring-boot-websocket_2:
    image: spring-boot-websocket
    container_name: spring-boot-websocket_2
    environment:
      DATABASE_USERNAME: "khanh"
      DATABASE_PASSWORD: "123456"
      DATABASE_HOST: "postgresql"
      DATABASE_NAME: "test"
      DATABASE_PORT: 5432
    ports:
      - 8082:8080
    networks:
      - huongdanjava
     
  spring-boot-websocket_3:
    image: spring-boot-websocket
    container_name: spring-boot-websocket_3
    environment:
      DATABASE_USERNAME: "khanh"
      DATABASE_PASSWORD: "123456"
      DATABASE_HOST: "postgresql"
      DATABASE_NAME: "test"
      DATABASE_PORT: 5432
    ports:
      - 8083:8080
    networks:
      - huongdanjava
      
  nginx:
    image: nginx:0.0.1
    ports:
      - 80:80

networks:
  huongdanjava:
    driver: bridge