/** Generated by the 'WIRING' default template from graphql-java-generator */
package com.huongdanjava.graphql.util;

/**
 * @author generated by graphql-java-generator
 * @see <a href="https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.graphql.execution.RuntimeWiringConfigurer;
import org.springframework.stereotype.Component;

import graphql.schema.GraphQLScalarType;

/**
 * Thanks to spring-graphql, the POJO classes are auto-magically discovered and mapped. But the custom scalars still needs to be 'manually' wired.
 * This is the objective of this class.
 * <BR/><BR/>
 * Based on the https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/ tutorial
 * 
 * @author etienne-sf
 */
@Component("graphQLWiring${configuration.springBeanSuffix}")
@SuppressWarnings("unused")
public class GraphQLWiring implements RuntimeWiringConfigurer {

	/** The logger for this instance */
	protected Logger logger = LoggerFactory.getLogger(GraphQLWiring.class);

	public void configure(graphql.schema.idl.RuntimeWiring.Builder builder) {
		// No configured custom scalars
 	}
}
