spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: huongdanjava
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer