openapi: 3.0.3
info:
  title: Student Information Management System
  version: 1.0.0
servers:
- url: https://localhost:8081/api
paths:
  /students:
    get:
      operationId: getStudents
      parameters:
      - description: Class of students
        explode: true
        in: query
        name: clazz
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              example:
              - id: 1
                code: "001"
                name: Khanh
                age: 30
                address: Binh Dinh
                clazz: A
              - id: 2
                code: "002"
                name: Quan
                age: 25
                address: Ho Chi Minh
                clazz: B
              schema:
                items:
                  $ref: '#/components/schemas/Student'
                type: array
          description: Get all students information
      summary: "Get all students information, can be filtered by clazz name"
      x-accepts: application/json
  /students/names:
    get:
      operationId: getStudentNames
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: Get student information
      summary: Get student names
      x-accepts: application/json
components:
  schemas:
    Student:
      example:
        code: code
        address: address
        name: name
        id: 0
        clazz: clazz
        age: 6
      properties:
        id:
          format: int64
          type: integer
        code:
          type: string
        name:
          type: string
        age:
          format: int64
          type: integer
        address:
          type: string
        clazz:
          type: string
      type: object
