apiVersion: v1
kind: Service
metadata:
  name: spring-boot-docker-compose-app-service
spec:
  selector:
    {{- include "spring-boot-docker-compose.labels" . | indent 4 }}
  ports:
  - protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: 8080
  type: {{ .Values.service.type }}