services:
  activemq:
    image: apache/activemq-classic:latest
    container_name: 'activemq'
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - ./activemq_data:/data/activemq
      - ./activemq_log:/var/log/activemq