services:
  postgresql:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "khanh"
      POSTGRES_DB: "test"
    volumes:
      - /Users/khanhnguyenj/data:/var/lib/postgresql/data
    networks:
      - huongdanjava

  spring_boot_docker_compose_1:
    image: spring-boot-docker-compose
    container_name: spring_boot_docker_compose_1
    depends_on:
      - postgresql
    environment:
      DATABASE_USERNAME: "khanh"
      DATABASE_PASSWORD: "123456"
      DATABASE_HOST: "postgresql"
      DATABASE_NAME: "test"
      DATABASE_PORT: 5432
    ports:
      - 8081:8080
    networks:
      - huongdanjava

  spring_boot_docker_compose_2:
    image: spring-boot-docker-compose
    container_name: spring_boot_docker_compose_2
    depends_on:
      - postgresql
    environment:
      DATABASE_USERNAME: "khanh"
      DATABASE_PASSWORD: "123456"
      DATABASE_HOST: "postgresql"
      DATABASE_NAME: "test"
      DATABASE_PORT: 5432
    ports:
      - 8082:8080
    networks:
      - huongdanjava

  spring_boot_docker_compose_3:
    image: spring-boot-docker-compose
    container_name: spring_boot_docker_compose_3
    depends_on:
      - postgresql
    environment:
      DATABASE_USERNAME: "khanh"
      DATABASE_PASSWORD: "123456"
      DATABASE_HOST: "postgresql"
      DATABASE_NAME: "test"
      DATABASE_PORT: 5432
    ports:
      - 8083:8080
    networks:
      - huongdanjava

  nginx:
    image: nginx:0.0.1
    ports:
      - 80:80

networks:
  huongdanjava:
    driver: bridge