CREATE TABLE orders
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_number   UUID                                    NOT NULL,
    customer_id    BIGINT                                  NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    total_amount   DECIMAL(19, 2)                          NOT NULL,
    currency       VARCHAR(255)                            NOT NULL,
    payment_method VARCHAR(255)                            NOT NULL,
    created_at     TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at     TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders
    ADD CONSTRAINT uc_orders_ordernumber UNIQUE (order_number);

CREATE TABLE order_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id     BIGINT,
    product_id   BIGINT,
    product_name VARCHAR(255),
    unit_price   DECIMAL,
    quantity     INTEGER,
    total_price  DECIMAL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE products
(
    id       BIGINT NOT NULL,
    name     VARCHAR(255),
    price    DECIMAL,
    currency VARCHAR(255),
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE saga_history
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    saga_id    UUID                                    NOT NULL,
    step       VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    message    TEXT,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_saga_history PRIMARY KEY (id)
);

CREATE TABLE saga_instance
(
    id           UUID                           NOT NULL,
    order_id     BIGINT                         NOT NULL,
    status       VARCHAR(255)                   NOT NULL,
    current_step VARCHAR(255)                   NOT NULL,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    version      BIGINT,
    CONSTRAINT pk_saga_instance PRIMARY KEY (id)
);

ALTER TABLE saga_instance
    ADD CONSTRAINT uc_saga_instance_orderid UNIQUE (order_id);