openapi: 3.0.3
info:
  title: Student Information Management System
  version: 1.0.0
servers:
  - url: https://localhost:8081/api
paths:
  /students:
    get:
      operationId: getStudents
      summary: Get all students
      responses:
        200:
          description: Get all students successfully
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Student'
              example: [{ "id": 1, "code": "001", "name": "Khanh" }, { "id": 2, "code": "002", "name": "Quan" }]
  /students/{id}:
    get:
      operationId: getStudentById
      summary: Get a student by id
      parameters:
        - name: id
          in: path
          description: "Id of the Student"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Get student information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
              example: { "id": 1, "code": "001", "name": "Khanh" }
    delete:
      operationId: deleteStudentById
      summary: Delete a student by id
      parameters:
        - name: id
          in: path
          description: "Id of the Student"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Delete student information successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example: { "message": "Student deleted!"}
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        name:
          type: string
    Response:
      type: object
      properties:
        message:
          type: string
