CREATE TABLE payments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    saga_id        UUID                                    NOT NULL,
    order_number   UUID                                    NOT NULL,
    customer_id    BIGINT                                  NOT NULL,
    amount         DECIMAL(19, 2)                          NOT NULL,
    currency       VARCHAR(3)                              NOT NULL,
    payment_method VARCHAR(255)                            NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    created_at     TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at     TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (id)
);