services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongodb_data:/data
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=khanh
      - ME_CONFIG_BASICAUTH_PASSWORD=123456

networks:
  huongdanjava:
    driver: bridge