CREATE TABLE product_stock
(
    product_id         INTEGER                        NOT NULL,
    available_quantity INTEGER                        NOT NULL,
    reserved_quantity  INTEGER                        NOT NULL,
    updated_at         TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    version            INTEGER                        NOT NULL,
    CONSTRAINT pk_product_stock PRIMARY KEY (product_id)
);

CREATE TABLE stock_reservations
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    saga_id      UUID                                    NOT NULL,
    order_number UUID                                    NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT pk_stock_reservations PRIMARY KEY (id)
);

ALTER TABLE stock_reservations
    ADD CONSTRAINT uc_stock_reservations_sagaid UNIQUE (saga_id);

CREATE TABLE stock_reservation_items
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_id BIGINT                                  NOT NULL,
    product_id     BIGINT                                  NOT NULL,
    quantity       INTEGER                                 NOT NULL,
    CONSTRAINT pk_stock_reservation_items PRIMARY KEY (id)
);

ALTER TABLE stock_reservation_items
    ADD CONSTRAINT FK_STOCK_RESERVATION_ITEMS_ON_RESERVATION FOREIGN KEY (reservation_id) REFERENCES stock_reservations (id);