apiVersion: v1
kind: Service
metadata:
  name: spring-boot-docker-compose-app-service
spec:
  selector:
    app: spring-boot-docker-compose
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer