debezium.source.database.hostname=postgres
debezium.source.database.port=5432
debezium.source.database.user=khanh
debezium.source.database.password=123456
debezium.source.database.dbname=debezium_example
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector

debezium.source.topic.prefix=debezium

debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=0

debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=data/schema-history.dat

debezium.source.plugin.name=pgoutput

debezium.sink.type=kafka
debezium.sink.kafka.producer.bootstrap.servers=kafka:29092
debezium.sink.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
debezium.sink.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer