services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq_data/:/var/lib/rabbitmq
      - ./rabbitmq_log/:/var/log/rabbitmq